# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

Challenge 1: Flatten a nested list
"""

#Concepts:List comprehesion

nested = [[1,2],[3,4],[5]]
matrix=[]
flat = [item for sublist in nested for item in sublist]
print(flat)

"""Challenge 2: check anagram"""

#Concepts: Sorted()

s1 = "listen"
s2 = "silent"
print(sorted(s1) == sorted(s2))

"""Challenge 3: find missing number"""

#Concepts: set()
'''HINt : compare with full range using set difference.'''

num = [1,2,4,5]
expected = set(range(1,6))
current = set(num)
missing = expected-current
print(missing)

"""Challenge 4 : gruop words by fisrt letter"""

#concepts: dict, setdefualt()

words = ["apple","ant","banana","bat"]
gruops = {}
for word in words:
  gruops.setdefault(word[0],[].append(word))
print(gruops)

"""Challege 5: Remove empty values"""

#concepts: dictionary comprehesion

data = {"a":1,"b":None,"c":3,"d":None}
clean = {k: v for k, v in data.items() if v is not None}
print(clean)