# -*- coding: utf-8 -*-
"""Day 37 challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfhCmVC_tLAWFNDOCKEiYsgWrY7kNG94
"""

sub = ['maths','english','telugu']
marks = [43,84,90]
l = list(sub)
print(l)

print(marks)
sum_m = sum(marks)
print(sum_m)

n = len(marks)
average = sum_m / n
print(f'total marks: {sum_m}')
print(f'average marks: {average:.2f}')

def calculate_grade(marks):
  if marks <0 or marks>100:
    return "Invalid marks"

    if marks >=90:
      return "A"
    elif marks >=75:
      return"B"
    elif marks >=50:
      return "C"
    elif marks <50:
      return"D"
    else:
      return"F"

student_marks = 67
final_grade = calculate_grade(student_marks)
print(f'marks: {student_marks}, grade:{final_grade}')