# -*- coding: utf-8 -*-
"""Day 34 challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOloKA3raJ1PeAVoR06Dz0c6L5EYTfME

Remove Duplicates & Preserve Order
"""

#Concepts: set(),list,loop
ids = [101,102,101,103,102,101]
s= set(ids)
print(s)
my_list= list(range(10))
print(my_list)

for i in ids:
  print(i)

"""Frequency Counter"""

#Concept; dict,get(),loop
products= ['apple','banan','apple','orange','banana','apple']
counts={}
for item in products:
  if item in counts:
    counts[item] +=1
  else:
   counts[item] =1
print(counts)

"""Find top score"""

#Concepts: max(),dict
marks = {'a':85,'b':92,'c':82}
marks['c']=88
marks.update({'c':88})
print(marks)
highest = max(marks.values())
print(highest)

"""Common Elements in two lists"""

#Concepts: set(),intersection()
skill1= ['python','sql','excel']
skill2= ['sql','power bi','python']
common = []
for item in skill1:
  if item in skill2:
    common.append(item)
print(common)

"""Sort deictionary by values

"""

# Concepts; sorted()
prices = {'apple':50,'banana':20,'orange':30}
sort_prices = {k: v for k, v in sorted(prices.items(), key=lambda item: item[1])}
print(sort_prices)